// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace Lab3
{
    public partial class BankMarketing
    {
        /// <summary>
        /// model input class for BankMarketing.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(0)]
            [ColumnName(@"age")]
            public float Age { get; set; }

            [LoadColumn(1)]
            [ColumnName(@"job")]
            public string Job { get; set; }

            [LoadColumn(2)]
            [ColumnName(@"marital")]
            public string Marital { get; set; }

            [LoadColumn(3)]
            [ColumnName(@"education")]
            public string Education { get; set; }

            [LoadColumn(4)]
            [ColumnName(@"default")]
            public bool Default { get; set; }

            [LoadColumn(5)]
            [ColumnName(@"balance")]
            public float Balance { get; set; }

            [LoadColumn(6)]
            [ColumnName(@"housing")]
            public bool Housing { get; set; }

            [LoadColumn(7)]
            [ColumnName(@"loan")]
            public bool Loan { get; set; }

            [LoadColumn(8)]
            [ColumnName(@"contact")]
            public string Contact { get; set; }

            [LoadColumn(9)]
            [ColumnName(@"day")]
            public float Day { get; set; }

            [LoadColumn(10)]
            [ColumnName(@"month")]
            public string Month { get; set; }

            [LoadColumn(11)]
            [ColumnName(@"duration")]
            public float Duration { get; set; }

            [LoadColumn(12)]
            [ColumnName(@"campaign")]
            public float Campaign { get; set; }

            [LoadColumn(13)]
            [ColumnName(@"pdays")]
            public float Pdays { get; set; }

            [LoadColumn(14)]
            [ColumnName(@"previous")]
            public float Previous { get; set; }

            [LoadColumn(15)]
            [ColumnName(@"poutcome")]
            public string Poutcome { get; set; }

            [LoadColumn(16)]
            [ColumnName(@"y")]
            public bool Y { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for BankMarketing.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"age")]
            public float Age { get; set; }

            [ColumnName(@"job")]
            public float[] Job { get; set; }

            [ColumnName(@"marital")]
            public float[] Marital { get; set; }

            [ColumnName(@"education")]
            public float[] Education { get; set; }

            [ColumnName(@"default")]
            public float Default { get; set; }

            [ColumnName(@"balance")]
            public float Balance { get; set; }

            [ColumnName(@"housing")]
            public float Housing { get; set; }

            [ColumnName(@"loan")]
            public float Loan { get; set; }

            [ColumnName(@"contact")]
            public float[] Contact { get; set; }

            [ColumnName(@"day")]
            public float Day { get; set; }

            [ColumnName(@"month")]
            public float[] Month { get; set; }

            [ColumnName(@"duration")]
            public float Duration { get; set; }

            [ColumnName(@"campaign")]
            public float Campaign { get; set; }

            [ColumnName(@"pdays")]
            public float Pdays { get; set; }

            [ColumnName(@"previous")]
            public float Previous { get; set; }

            [ColumnName(@"poutcome")]
            public float[] Poutcome { get; set; }

            [ColumnName(@"y")]
            public bool Y { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"PredictedLabel")]
            public bool PredictedLabel { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

            [ColumnName(@"Probability")]
            public float Probability { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("BankMarketing.mlnet");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

    }
}
